name : Laravel

on:
   push:
      branches: [master]
   pull_request:
      branches: [master]
      
jobs:
   deploy:
      runs-on: ubuntu-20.04
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Sync
           env:
             dest: "ubuntu@dev.kelasdevops.xyz:~/dev.kelasdevops.xyz/"
           run: |
             echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
             chmod 600 ~/deploy_key
             rsync -chav --delete \
               -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \
               --exclude ~/deploy_key \
               --exclude .git/ \
               --exclude .github/ \
               --exclude storage/ \
               --exclude .env \
               ./ ${{env.dest}}
             ssh -i ~/deploy_key -o StrictHostKeyChecking=no ubuntu@dev.kelasdevops.xyz \
               'cd ~/dev.kelasdevops.xyz && composer install'
